services:
  - type: web
    name: pumpfun-base
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
